"""
:synopsis: Supported metric calculations to use on validation data with NPU API for training.
.. moduleauthor:: Naval Bhandari <naval@neuro-ai.co.uk>
"""

Accuracy = "Accuracy"
# Binary_accuracy = "Binary_accuracy"
# Binary_cross_entropy = "Binary_cross_entropy"
# Categorical_accuracy = "Categorical_accuracy"
CategoricalCrossEntropy = "Categorical_cross_entropy"
# Categorical_hinge = "Categorical_hinge"
# Cosine_similarity = "Cosine_similarity"
# Hinge = "Hinge"
# Kl_divergence = "Kl_divergence"
# Log_cosh_error = "Log_cosh_error"
# Mean = "Mean"
MeanAbsoluteError = "Mean_absolute_error"
# Mean_absolute_percentage_error = "Mean_absolute_percentage_error"
# Mean_relative_error = "Mean_relative_error"
MeanSquaredError = "Mean_squared_error"
# Mean_squared_logarithmic_error = "Mean_squared_logarithmic_error"
# Mean_tensor = "Mean_tensor"
# Poisson = "Poisson"
# Root_mean_squared_error = "Root_mean_squared_error"
# Sensitivity_at_specificity = "Sensitivity_at_specificity"
# Sparse_categorical_accuracy = "Sparse_categorical_accuracy"
# Sparse_categorical_cross_entropy = "Sparse_categorical_cross_entropy"
# Sparse_top_k_categorical_accuracy = "Sparse_top_k_categorical_accuracy"
# Squared_hinge = "Squared_hinge"
# Sum = "Sum"
# Top_k_categorical_accuracy = "Top_k_categorical_accuracy"
